import { api } from './api/apiClient';
import { ENDPOINTS, buildUrl } from './api/endpoints';
import { storageService } from './storageService';

// Extended mock data for 100 chicken dishes
export const mockMenuItems = [
  {
    id: 1,
    name: "Classic Crispy Chicken",
    description: "Our signature crispy fried chicken with perfect seasoning.",
    price: 12.99,
    category: "fried-chicken",
    image: "/images/chicken-classic.jpg",
    rating: 4.8,
    reviews: 124,
    popular: true,
    available: true,
    spiceLevel: 2,
    prepTime: "15-20 min",
    calories: 320,
    tags: ["signature", "crispy", "fried"]
  },
  {
    id: 2,
    name: "Spicy Hot Wings",
    description: "Crispy chicken wings with our special spicy sauce.",
    price: 9.99,
    category: "wings",
    image: "/images/wings-spicy.jpg",
    rating: 4.7,
    reviews: 98,
    popular: true,
    available: true,
    spiceLevel: 4,
    prepTime: "12-15 min",
    calories: 380,
    tags: ["spicy", "wings", "hot"]
  },
  {
    id: 3,
    name: "BBQ Glazed Drumsticks",
    description: "Tender drumsticks glazed with smoky BBQ sauce.",
    price: 10.99,
    category: "grilled-chicken",
    image: "/images/drumsticks-bbq.jpg",
    rating: 4.6,
    reviews: 76,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "18-22 min",
    calories: 280,
    tags: ["bbq", "grilled", "smoky"]
  },
  {
    id: 4,
    name: "Honey Garlic Chicken Breast",
    description: "Juicy chicken breast with sweet honey garlic glaze.",
    price: 13.99,
    category: "grilled-chicken",
    image: "/images/chicken-breast-honey.jpg",
    rating: 4.9,
    reviews: 142,
    popular: true,
    available: true,
    spiceLevel: 1,
    prepTime: "20-25 min",
    calories: 240,
    tags: ["honey", "garlic", "healthy"]
  },
  {
    id: 5,
    name: "Chicken Caesar Wrap",
    description: "Grilled chicken strips with romaine lettuce and parmesan.",
    price: 8.99,
    category: "sandwiches",
    image: "/images/wrap-caesar.jpg",
    rating: 4.5,
    reviews: 87,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "8-12 min",
    calories: 350,
    tags: ["wrap", "healthy", "light"]
  },
  {
    id: 6,
    name: "Nashville Hot Chicken Sandwich",
    description: "Spicy fried chicken on a brioche bun with pickles.",
    price: 11.49,
    category: "sandwiches",
    image: "/images/sandwich-hot.jpg",
    rating: 4.7,
    reviews: 112,
    popular: true,
    available: true,
    spiceLevel: 5,
    prepTime: "10-15 min",
    calories: 420,
    tags: ["spicy", "sandwich", "nashville"]
  },
  {
    id: 7,
    name: "Teriyaki Chicken Bowl",
    description: "Steamed rice with teriyaki glazed chicken and vegetables.",
    price: 12.49,
    category: "bowls",
    image: "/images/bowl-teriyaki.jpg",
    rating: 4.6,
    reviews: 95,
    popular: true,
    available: true,
    spiceLevel: 1,
    prepTime: "15-20 min",
    calories: 480,
    tags: ["asian", "healthy", "rice"]
  },
  {
    id: 8,
    name: "Korean Fire Chicken",
    description: "Crispy chicken with Korean gochujang sauce.",
    price: 14.99,
    category: "fried-chicken",
    image: "/images/korean-fire.jpg",
    rating: 4.8,
    reviews: 134,
    popular: true,
    available: true,
    spiceLevel: 5,
    prepTime: "18-22 min",
    calories: 360,
    tags: ["korean", "fire", "spicy"]
  },
  {
    id: 9,
    name: "Lemon Herb Grilled Chicken",
    description: "Fresh lemon and herbs grilled chicken breast.",
    price: 13.49,
    category: "grilled-chicken",
    image: "/images/lemon-herb.jpg",
    rating: 4.7,
    reviews: 89,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "22-25 min",
    calories: 220,
    tags: ["healthy", "lemon", "light"]
  },
  {
    id: 10,
    name: "Chicken Tikka Masala",
    description: "Tender chicken in creamy tomato masala sauce.",
    price: 15.99,
    category: "indian",
    image: "/images/tikka-masala.jpg",
    rating: 4.9,
    reviews: 167,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "25-30 min",
    calories: 420,
    tags: ["indian", "curry", "creamy"]
  },
  {
    id: 11,
    name: "Buffalo Chicken Tacos",
    description: "Soft tacos with buffalo chicken and ranch.",
    price: 10.99,
    category: "mexican",
    image: "/images/buffalo-tacos.jpg",
    rating: 4.5,
    reviews: 78,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "12-15 min",
    calories: 380,
    tags: ["mexican", "buffalo", "tacos"]
  },
  {
    id: 12,
    name: "Cajun Spiced Chicken",
    description: "Cajun seasoned chicken with rice and beans.",
    price: 14.49,
    category: "southern",
    image: "/images/cajun-chicken.jpg",
    rating: 4.6,
    reviews: 92,
    popular: false,
    available: true,
    spiceLevel: 4,
    prepTime: "20-25 min",
    calories: 400,
    tags: ["cajun", "southern", "spicy"]
  },
  {
    id: 13,
    name: "Thai Basil Chicken",
    description: "Stir-fried chicken with Thai basil and jasmine rice.",
    price: 13.99,
    category: "thai",
    image: "/images/thai-basil.jpg",
    rating: 4.7,
    reviews: 105,
    popular: true,
    available: true,
    spiceLevel: 4,
    prepTime: "18-22 min",
    calories: 380,
    tags: ["thai", "basil", "asian"]
  },
  {
    id: 14,
    name: "Mediterranean Chicken Salad",
    description: "Grilled chicken with feta, olives, and Mediterranean dressing.",
    price: 11.99,
    category: "salads",
    image: "/images/mediterranean-salad.jpg",
    rating: 4.4,
    reviews: 67,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "10-12 min",
    calories: 320,
    tags: ["healthy", "mediterranean", "light"]
  },
  {
    id: 15,
    name: "Jerk Chicken",
    description: "Jamaican jerk seasoned chicken with rice and peas.",
    price: 14.99,
    category: "caribbean",
    image: "/images/jerk-chicken.jpg",
    rating: 4.8,
    reviews: 118,
    popular: true,
    available: true,
    spiceLevel: 5,
    prepTime: "22-25 min",
    calories: 390,
    tags: ["jerk", "caribbean", "spicy"]
  },
  {
    id: 16,
    name: "Chicken Parmesan",
    description: "Breaded chicken cutlet with marinara and mozzarella.",
    price: 15.49,
    category: "italian",
    image: "/images/chicken-parmesan.jpg",
    rating: 4.7,
    reviews: 125,
    popular: true,
    available: true,
    spiceLevel: 1,
    prepTime: "25-30 min",
    calories: 450,
    tags: ["italian", "parmesan", "cheesy"]
  },
  {
    id: 17,
    name: "Szechuan Chicken",
    description: "Spicy Szechuan style chicken with vegetables.",
    price: 14.49,
    category: "chinese",
    image: "/images/szechuan-chicken.jpg",
    rating: 4.6,
    reviews: 89,
    popular: false,
    available: true,
    spiceLevel: 5,
    prepTime: "20-25 min",
    calories: 370,
    tags: ["chinese", "szechuan", "spicy"]
  },
  {
    id: 18,
    name: "Chicken Shawarma",
    description: "Middle Eastern spiced chicken with tahini sauce.",
    price: 12.99,
    category: "middle-eastern",
    image: "/images/shawarma.jpg",
    rating: 4.5,
    reviews: 76,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "15-18 min",
    calories: 400,
    tags: ["middle-eastern", "shawarma", "tahini"]
  },
  {
    id: 19,
    name: "Honey Soy Glazed Chicken",
    description: "Sweet and savory honey soy glazed chicken.",
    price: 13.99,
    category: "asian",
    image: "/images/honey-soy.jpg",
    rating: 4.6,
    reviews: 94,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "18-22 min",
    calories: 340,
    tags: ["asian", "honey", "soy"]
  },
  {
    id: 20,
    name: "Chicken Fajitas",
    description: "Sizzling chicken fajitas with peppers and onions.",
    price: 14.99,
    category: "mexican",
    image: "/images/chicken-fajitas.jpg",
    rating: 4.7,
    reviews: 108,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "20-25 min",
    calories: 420,
    tags: ["mexican", "fajitas", "sizzling"]
  },
  {
    id: 21,
    name: "Butter Chicken",
    description: "Creamy butter chicken in rich tomato sauce.",
    price: 15.99,
    category: "indian",
    image: "/images/butter-chicken.jpg",
    rating: 4.8,
    reviews: 145,
    popular: true,
    available: true,
    spiceLevel: 2,
    prepTime: "25-30 min",
    calories: 430,
    tags: ["indian", "butter", "creamy"]
  },
  {
    id: 22,
    name: "Chicken Gyro",
    description: "Grilled chicken gyro with tzatziki sauce.",
    price: 11.49,
    category: "greek",
    image: "/images/chicken-gyro.jpg",
    rating: 4.5,
    reviews: 83,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "12-15 min",
    calories: 360,
    tags: ["greek", "gyro", "tzatziki"]
  },
  {
    id: 23,
    name: "Bang Bang Chicken",
    description: "Crispy chicken with spicy bang bang sauce.",
    price: 12.99,
    category: "asian",
    image: "/images/bang-bang.jpg",
    rating: 4.6,
    reviews: 91,
    popular: true,
    available: true,
    spiceLevel: 4,
    prepTime: "15-18 min",
    calories: 350,
    tags: ["asian", "bang bang", "spicy"]
  },
  {
    id: 24,
    name: "Chicken Katsu",
    description: "Japanese breaded chicken katsu with tonkatsu sauce.",
    price: 14.49,
    category: "japanese",
    image: "/images/chicken-katsu.jpg",
    rating: 4.7,
    reviews: 112,
    popular: true,
    available: true,
    spiceLevel: 1,
    prepTime: "20-25 min",
    calories: 410,
    tags: ["japanese", "katsu", "tonkatsu"]
  },
  {
    id: 25,
    name: "Chicken Enchiladas",
    description: "Chicken enchiladas with melted cheese and salsa.",
    price: 13.99,
    category: "mexican",
    image: "/images/chicken-enchiladas.jpg",
    rating: 4.6,
    reviews: 87,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "22-25 min",
    calories: 440,
    tags: ["mexican", "enchiladas", "cheesy"]
  },
  {
    id: 26,
    name: "Coconut Curry Chicken",
    description: "Creamy coconut curry chicken with jasmine rice.",
    price: 14.99,
    category: "thai",
    image: "/images/coconut-curry.jpg",
    rating: 4.7,
    reviews: 103,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "25-30 min",
    calories: 400,
    tags: ["thai", "coconut", "curry"]
  },
  {
    id: 27,
    name: "Chicken Marsala",
    description: "Italian style chicken marsala with mushrooms.",
    price: 15.49,
    category: "italian",
    image: "/images/chicken-marsala.jpg",
    rating: 4.6,
    reviews: 95,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "25-30 min",
    calories: 420,
    tags: ["italian", "marsala", "mushrooms"]
  },
  {
    id: 28,
    name: "Chicken Teriyaki Bowl",
    description: "Steamed rice with teriyaki chicken and vegetables.",
    price: 12.49,
    category: "japanese",
    image: "/images/teriyaki-bowl.jpg",
    rating: 4.5,
    reviews: 78,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "15-20 min",
    calories: 450,
    tags: ["japanese", "teriyaki", "bowl"]
  },
  {
    id: 29,
    name: "Chicken Quesadilla",
    description: "Grilled chicken quesadilla with cheese and peppers.",
    price: 10.99,
    category: "mexican",
    image: "/images/chicken-quesadilla.jpg",
    rating: 4.4,
    reviews: 69,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "10-12 min",
    calories: 380,
    tags: ["mexican", "quesadilla", "cheesy"]
  },
  {
    id: 30,
    name: "Chicken Tikka",
    description: "Traditional Indian spiced chicken tikka.",
    price: 14.99,
    category: "indian",
    image: "/images/chicken-tikka.jpg",
    rating: 4.7,
    reviews: 118,
    popular: true,
    available: true,
    spiceLevel: 4,
    prepTime: "20-25 min",
    calories: 360,
    tags: ["indian", "tikka", "spiced"]
  },
  {
    id: 31,
    name: "Crispy Chicken Tenders",
    description: "Six pieces of crispy chicken tenders with dipping sauce.",
    price: 11.99,
    category: "fried-chicken",
    image: "/images/chicken-tenders.jpg",
    rating: 4.5,
    reviews: 132,
    popular: true,
    available: true,
    spiceLevel: 1,
    prepTime: "12-15 min",
    calories: 340,
    tags: ["tenders", "kids", "crispy"]
  },
  {
    id: 32,
    name: "Honey Mustard Chicken",
    description: "Grilled chicken with sweet honey mustard glaze.",
    price: 13.49,
    category: "grilled-chicken",
    image: "/images/honey-mustard.jpg",
    rating: 4.6,
    reviews: 89,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "18-22 min",
    calories: 280,
    tags: ["honey", "mustard", "grilled"]
  },
  {
    id: 33,
    name: "Chicken Pho",
    description: "Vietnamese noodle soup with tender chicken.",
    price: 12.99,
    category: "vietnamese",
    image: "/images/chicken-pho.jpg",
    rating: 4.7,
    reviews: 107,
    popular: true,
    available: true,
    spiceLevel: 2,
    prepTime: "20-25 min",
    calories: 380,
    tags: ["vietnamese", "pho", "soup"]
  },
  {
    id: 34,
    name: "Chicken Satay",
    description: "Grilled chicken skewers with peanut sauce.",
    price: 13.99,
    category: "thai",
    image: "/images/chicken-satay.jpg",
    rating: 4.6,
    reviews: 94,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "15-18 min",
    calories: 320,
    tags: ["thai", "satay", "peanut"]
  },
  {
    id: 35,
    name: "Chicken Chimichanga",
    description: "Crispy chimichanga filled with seasoned chicken.",
    price: 12.49,
    category: "mexican",
    image: "/images/chimichanga.jpg",
    rating: 4.5,
    reviews: 76,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "20-25 min",
    calories: 420,
    tags: ["mexican", "chimichanga", "crispy"]
  },
  {
    id: 36,
    name: "Chicken Biriyani",
    description: "Fragrant basmati rice with spiced chicken.",
    price: 14.49,
    category: "indian",
    image: "/images/chicken-biriyani.jpg",
    rating: 4.8,
    reviews: 125,
    popular: true,
    available: true,
    spiceLevel: 4,
    prepTime: "30-35 min",
    calories: 480,
    tags: ["indian", "biriyani", "spiced"]
  },
  {
    id: 37,
    name: "Chicken Bulgogi",
    description: "Korean marinated chicken with vegetables.",
    price: 14.99,
    category: "korean",
    image: "/images/chicken-bulgogi.jpg",
    rating: 4.7,
    reviews: 109,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "22-25 min",
    calories: 390,
    tags: ["korean", "bulgogi", "marinated"]
  },
  {
    id: 38,
    name: "Chicken Souvlaki",
    description: "Greek style grilled chicken skewers with pita.",
    price: 11.99,
    category: "greek",
    image: "/images/chicken-souvlaki.jpg",
    rating: 4.6,
    reviews: 84,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "15-18 min",
    calories: 340,
    tags: ["greek", "souvlaki", "skewers"]
  },
  {
    id: 39,
    name: "Chicken Pad Thai",
    description: "Classic Thai noodles with chicken and peanuts.",
    price: 13.49,
    category: "thai",
    image: "/images/pad-thai.jpg",
    rating: 4.7,
    reviews: 115,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "18-22 min",
    calories: 410,
    tags: ["thai", "pad thai", "noodles"]
  },
  {
    id: 40,
    name: "Chicken Carbonara",
    description: "Creamy pasta with grilled chicken and parmesan.",
    price: 14.99,
    category: "italian",
    image: "/images/chicken-carbonara.jpg",
    rating: 4.6,
    reviews: 97,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "20-25 min",
    calories: 460,
    tags: ["italian", "carbonara", "pasta"]
  },
  {
    id: 41,
    name: "Chicken Shawarma Bowl",
    description: "Rice bowl with shawarma chicken and toppings.",
    price: 12.99,
    category: "middle-eastern",
    image: "/images/shawarma-bowl.jpg",
    rating: 4.5,
    reviews: 88,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "15-18 min",
    calories: 400,
    tags: ["middle-eastern", "shawarma", "bowl"]
  },
  {
    id: 42,
    name: "Chicken Ramen",
    description: "Rich broth with tender chicken and noodles.",
    price: 13.99,
    category: "japanese",
    image: "/images/chicken-ramen.jpg",
    rating: 4.6,
    reviews: 102,
    popular: true,
    available: true,
    spiceLevel: 2,
    prepTime: "20-25 min",
    calories: 420,
    tags: ["japanese", "ramen", "broth"]
  },
  {
    id: 43,
    name: "Chicken Pozole",
    description: "Mexican hominy soup with seasoned chicken.",
    price: 12.49,
    category: "mexican",
    image: "/images/chicken-pozole.jpg",
    rating: 4.5,
    reviews: 79,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "25-30 min",
    calories: 380,
    tags: ["mexican", "pozole", "soup"]
  },
  {
    id: 44,
    name: "Chicken Tikka Masala Bowl",
    description: "Rice bowl with tikka masala chicken.",
    price: 13.99,
    category: "indian",
    image: "/images/tikka-bowl.jpg",
    rating: 4.7,
    reviews: 111,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "20-25 min",
    calories: 430,
    tags: ["indian", "tikka", "bowl"]
  },
  {
    id: 45,
    name: "Chicken Donburi",
    description: "Japanese rice bowl with glazed chicken.",
    price: 12.99,
    category: "japanese",
    image: "/images/chicken-donburi.jpg",
    rating: 4.6,
    reviews: 93,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "15-18 min",
    calories: 380,
    tags: ["japanese", "donburi", "rice"]
  },
  {
    id: 46,
    name: "Chicken Tandoori",
    description: "Traditional tandoor roasted chicken with mint chutney.",
    price: 14.99,
    category: "indian",
    image: "/images/chicken-tandoori.jpg",
    rating: 4.8,
    reviews: 135,
    popular: true,
    available: true,
    spiceLevel: 4,
    prepTime: "25-30 min",
    calories: 370,
    tags: ["indian", "tandoori", "traditional"]
  },
  {
    id: 47,
    name: "Chicken Bulgur Bowl",
    description: "Middle eastern bowl with chicken and bulgur.",
    price: 11.99,
    category: "middle-eastern",
    image: "/images/bulgur-bowl.jpg",
    rating: 4.5,
    reviews: 74,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "18-22 min",
    calories: 360,
    tags: ["middle-eastern", "bulgur", "healthy"]
  },
  {
    id: 48,
    name: "Chicken Kimchi Fried Rice",
    description: "Korean style fried rice with kimchi and chicken.",
    price: 12.99,
    category: "korean",
    image: "/images/kimchi-fried-rice.jpg",
    rating: 4.6,
    reviews: 87,
    popular: false,
    available: true,
    spiceLevel: 4,
    prepTime: "15-18 min",
    calories: 390,
    tags: ["korean", "kimchi", "fried rice"]
  },
  {
    id: 49,
    name: "Chicken Gyro Bowl",
    description: "Rice bowl with gyro chicken and tzatziki.",
    price: 12.49,
    category: "greek",
    image: "/images/gyro-bowl.jpg",
    rating: 4.5,
    reviews: 81,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "12-15 min",
    calories: 370,
    tags: ["greek", "gyro", "bowl"]
  },
  {
    id: 50,
    name: "Chicken Laksa",
    description: "Spicy Malaysian noodle soup with chicken.",
    price: 13.99,
    category: "malaysian",
    image: "/images/chicken-laksa.jpg",
    rating: 4.7,
    reviews: 106,
    popular: true,
    available: true,
    spiceLevel: 5,
    prepTime: "22-25 min",
    calories: 410,
    tags: ["malaysian", "laksa", "spicy"]
  },
  {
    id: 51,
    name: "Crispy Korean Chicken",
    description: "Double-fried Korean style chicken with sauce.",
    price: 14.99,
    category: "korean",
    image: "/images/korean-crispy.jpg",
    rating: 4.8,
    reviews: 128,
    popular: true,
    available: true,
    spiceLevel: 4,
    prepTime: "20-25 min",
    calories: 360,
    tags: ["korean", "crispy", "double-fried"]
  },
  {
    id: 52,
    name: "Chicken Tikka Masala Pizza",
    description: "Pizza with tikka masala chicken and cheese.",
    price: 15.49,
    category: "fusion",
    image: "/images/tikka-pizza.jpg",
    rating: 4.6,
    reviews: 95,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "25-30 min",
    calories: 480,
    tags: ["fusion", "pizza", "indian"]
  },
  {
    id: 53,
    name: "Chicken Teriyaki Burger",
    description: "Burger with teriyaki glazed chicken and vegetables.",
    price: 12.99,
    category: "fusion",
    image: "/images/teriyaki-burger.jpg",
    rating: 4.5,
    reviews: 82,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "12-15 min",
    calories: 420,
    tags: ["fusion", "burger", "teriyaki"]
  },
  {
    id: 54,
    name: "Chicken Shawarma Pizza",
    description: "Pizza with shawarma chicken and Middle Eastern spices.",
    price: 14.99,
    category: "fusion",
    image: "/images/shawarma-pizza.jpg",
    rating: 4.7,
    reviews: 108,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "25-30 min",
    calories: 460,
    tags: ["fusion", "pizza", "shawarma"]
  },
  {
    id: 55,
    name: "Chicken Tikka Wrap",
    description: "Wrap with Indian spiced chicken and vegetables.",
    price: 11.99,
    category: "indian",
    image: "/images/tikka-wrap.jpg",
    rating: 4.6,
    reviews: 89,
    popular: false,
    available: true,
    spiceLevel: 4,
    prepTime: "10-12 min",
    calories: 380,
    tags: ["indian", "tikka", "wrap"]
  },
  {
    id: 56,
    name: "Chicken Katsu Burger",
    description: "Burger with Japanese katsu chicken and tonkatsu sauce.",
    price: 13.99,
    category: "fusion",
    image: "/images/katsu-burger.jpg",
    rating: 4.7,
    reviews: 97,
    popular: true,
    available: true,
    spiceLevel: 1,
    prepTime: "15-18 min",
    calories: 440,
    tags: ["fusion", "burger", "japanese"]
  },
  {
    id: 57,
    name: "Chicken Pad See Ew",
    description: "Thai stir-fried noodles with chicken and vegetables.",
    price: 13.49,
    category: "thai",
    image: "/images/pad-see-ew.jpg",
    rating: 4.6,
    reviews: 91,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "18-22 min",
    calories: 400,
    tags: ["thai", "noodles", "stir-fry"]
  },
  {
    id: 58,
    name: "Chicken Biryani Bowl",
    description: "Rice bowl with biryani spices and chicken.",
    price: 13.99,
    category: "indian",
    image: "/images/biryani-bowl.jpg",
    rating: 4.7,
    reviews: 103,
    popular: true,
    available: true,
    spiceLevel: 4,
    prepTime: "22-25 min",
    calories: 450,
    tags: ["indian", "biryani", "bowl"]
  },
  {
    id: 59,
    name: "Chicken Bulgogi Bowl",
    description: "Rice bowl with Korean bulgogi chicken.",
    price: 13.99,
    category: "korean",
    image: "/images/bulgogi-bowl.jpg",
    rating: 4.7,
    reviews: 101,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "18-22 min",
    calories: 400,
    tags: ["korean", "bulgogi", "bowl"]
  },
  {
    id: 60,
    name: "Chicken Katsu Curry",
    description: "Japanese curry with chicken katsu and rice.",
    price: 14.99,
    category: "japanese",
    image: "/images/katsu-curry.jpg",
    rating: 4.8,
    reviews: 119,
    popular: true,
    available: true,
    spiceLevel: 2,
    prepTime: "20-25 min",
    calories: 470,
    tags: ["japanese", "katsu", "curry"]
  },
  {
    id: 61,
    name: "Chicken Adobo",
    description: "Filipino style chicken adobo with rice.",
    price: 13.49,
    category: "filipino",
    image: "/images/chicken-adobo.jpg",
    rating: 4.6,
    reviews: 88,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "25-30 min",
    calories: 390,
    tags: ["filipino", "adobo", "soy sauce"]
  },
  {
    id: 62,
    name: "Chicken Kabsa",
    description: "Saudi Arabian rice dish with spiced chicken.",
    price: 14.99,
    category: "saudi",
    image: "/images/chicken-kabsa.jpg",
    rating: 4.7,
    reviews: 94,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "30-35 min",
    calories: 450,
    tags: ["saudi", "kabsa", "arabian"]
  },
  {
    id: 63,
    name: "Chicken Jollof Rice",
    description: "West African jollof rice with seasoned chicken.",
    price: 13.99,
    category: "west-african",
    image: "/images/jollof-rice.jpg",
    rating: 4.6,
    reviews: 85,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "25-30 min",
    calories: 420,
    tags: ["west-african", "jollof", "rice"]
  },
  {
    id: 64,
    name: "Chicken Tagine",
    description: "Moroccan slow-cooked chicken with vegetables.",
    price: 15.49,
    category: "moroccan",
    image: "/images/chicken-tagine.jpg",
    rating: 4.8,
    reviews: 107,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "35-40 min",
    calories: 430,
    tags: ["moroccan", "tagine", "slow-cooked"]
  },
  {
    id: 65,
    name: "Chicken Nasi Goreng",
    description: "Indonesian fried rice with chicken and sambal.",
    price: 13.49,
    category: "indonesian",
    image: "/images/nasi-goreng.jpg",
    rating: 4.6,
    reviews: 83,
    popular: false,
    available: true,
    spiceLevel: 4,
    prepTime: "18-22 min",
    calories: 410,
    tags: ["indonesian", "nasi goreng", "fried rice"]
  },
  {
    id: 66,
    name: "Chicken Khichdi",
    description: "Indian comfort food with spiced chicken.",
    price: 12.99,
    category: "indian",
    image: "/images/chicken-khichdi.jpg",
    rating: 4.5,
    reviews: 76,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "25-30 min",
    calories: 380,
    tags: ["indian", "khichdi", "comfort food"]
  },
  {
    id: 67,
    name: "Chicken Empanadas",
    description: "Crispy empanadas filled with seasoned chicken.",
    price: 11.99,
    category: "latin-american",
    image: "/images/chicken-empanadas.jpg",
    rating: 4.4,
    reviews: 71,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "20-25 min",
    calories: 360,
    tags: ["latin-american", "empanadas", "crispy"]
  },
  {
    id: 68,
    name: "Chicken Soto Ayam",
    description: "Indonesian chicken soup with rice and sambal.",
    price: 12.49,
    category: "indonesian",
    image: "/images/soto-ayam.jpg",
    rating: 4.6,
    reviews: 89,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "20-25 min",
    calories: 340,
    tags: ["indonesian", "soto", "soup"]
  },
  {
    id: 69,
    name: "Chicken Poutine",
    description: "Canadian poutine with chicken gravy and cheese curds.",
    price: 12.99,
    category: "canadian",
    image: "/images/chicken-poutine.jpg",
    rating: 4.5,
    reviews: 78,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "15-18 min",
    calories: 450,
    tags: ["canadian", "poutine", "cheese"]
  },
  {
    id: 70,
    name: "Chicken Bobotie",
    description: "South African spiced meat dish with chicken.",
    price: 14.49,
    category: "south-african",
    image: "/images/chicken-bobotie.jpg",
    rating: 4.7,
    reviews: 92,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "30-35 min",
    calories: 400,
    tags: ["south-african", "bobotie", "spiced"]
  },
  {
    id: 71,
    name: "Chicken Pilaf",
    description: "Persian rice pilaf with aromatic spices and chicken.",
    price: 13.99,
    category: "persian",
    image: "/images/chicken-pilaf.jpg",
    rating: 4.6,
    reviews: 86,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "30-35 min",
    calories: 410,
    tags: ["persian", "pilaf", "aromatic"]
  },
  {
    id: 72,
    name: "Chicken Escabeche",
    description: "Latin American pickled chicken with vegetables.",
    price: 12.99,
    category: "latin-american",
    image: "/images/chicken-escabeche.jpg",
    rating: 4.5,
    reviews: 74,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "25-30 min",
    calories: 350,
    tags: ["latin-american", "escabeche", "pickled"]
  },
  {
    id: 73,
    name: "Chicken Paella",
    description: "Spanish paella with saffron and mixed chicken.",
    price: 15.99,
    category: "spanish",
    image: "/images/chicken-paella.jpg",
    rating: 4.8,
    reviews: 115,
    popular: true,
    available: true,
    spiceLevel: 2,
    prepTime: "35-40 min",
    calories: 480,
    tags: ["spanish", "paella", "saffron"]
  },
  {
    id: 74,
    name: "Chicken Tom Yum Soup",
    description: "Spicy Thai soup with chicken and aromatic herbs.",
    price: 12.99,
    category: "thai",
    image: "/images/tom-yum.jpg",
    rating: 4.7,
    reviews: 109,
    popular: true,
    available: true,
    spiceLevel: 5,
    prepTime: "18-22 min",
    calories: 320,
    tags: ["thai", "tom yum", "spicy"]
  },
  {
    id: 75,
    name: "Chicken Cornish Pasty",
    description: "British pastry filled with chicken and vegetables.",
    price: 11.99,
    category: "british",
    image: "/images/chicken-pasty.jpg",
    rating: 4.5,
    reviews: 77,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "25-30 min",
    calories: 380,
    tags: ["british", "pasty", "pastry"]
  },
  {
    id: 76,
    name: "Chicken Banh Mi",
    description: "Vietnamese sandwich with grilled chicken and pickles.",
    price: 10.49,
    category: "vietnamese",
    image: "/images/banh-mi.jpg",
    rating: 4.6,
    reviews: 98,
    popular: true,
    available: true,
    spiceLevel: 2,
    prepTime: "12-15 min",
    calories: 340,
    tags: ["vietnamese", "banh mi", "sandwich"]
  },
  {
    id: 77,
    name: "Chicken Kibbeh",
    description: "Levantine bulgur and chicken dumplings.",
    price: 12.49,
    category: "levantine",
    image: "/images/chicken-kibbeh.jpg",
    rating: 4.5,
    reviews: 73,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "30-35 min",
    calories: 360,
    tags: ["levantine", "kibbeh", "bulgur"]
  },
  {
    id: 78,
    name: "Chicken Arepa",
    description: "Colombian flatbread stuffed with seasoned chicken.",
    price: 9.99,
    category: "colombian",
    image: "/images/chicken-arepa.jpg",
    rating: 4.4,
    reviews: 68,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "15-18 min",
    calories: 320,
    tags: ["colombian", "arepa", "flatbread"]
  },
  {
    id: 79,
    name: "Chicken Couscous",
    description: "Moroccan couscous with vegetables and spiced chicken.",
    price: 14.49,
    category: "moroccan",
    image: "/images/chicken-couscous.jpg",
    rating: 4.7,
    reviews: 101,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "30-35 min",
    calories: 420,
    tags: ["moroccan", "couscous", "vegetables"]
  },
  {
    id: 80,
    name: "Chicken Biryani Biryani",
    description: "Hyderabadi style biryani with tender chicken.",
    price: 14.99,
    category: "indian",
    image: "/images/hyderabadi-biryani.jpg",
    rating: 4.8,
    reviews: 127,
    popular: true,
    available: true,
    spiceLevel: 4,
    prepTime: "35-40 min",
    calories: 460,
    tags: ["indian", "hyderabadi", "biryani"]
  },
  {
    id: 81,
    name: "Chicken Roti",
    description: "Caribbean roti with spiced chicken curry.",
    price: 12.99,
    category: "caribbean",
    image: "/images/chicken-roti.jpg",
    rating: 4.6,
    reviews: 85,
    popular: false,
    available: true,
    spiceLevel: 4,
    prepTime: "20-25 min",
    calories: 380,
    tags: ["caribbean", "roti", "curry"]
  },
  {
    id: 82,
    name: "Chicken Gumbo",
    description: "Louisiana gumbo with chicken and andouille.",
    price: 13.49,
    category: "southern",
    image: "/images/chicken-gumbo.jpg",
    rating: 4.6,
    reviews: 81,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "30-35 min",
    calories: 400,
    tags: ["southern", "gumbo", "cajun"]
  },
  {
    id: 83,
    name: "Chicken Piri Piri",
    description: "Portuguese style chicken with piri piri sauce.",
    price: 13.99,
    category: "portuguese",
    image: "/images/chicken-piri-piri.jpg",
    rating: 4.7,
    reviews: 96,
    popular: true,
    available: true,
    spiceLevel: 5,
    prepTime: "22-25 min",
    calories: 360,
    tags: ["portuguese", "piri piri", "spicy"]
  },
  {
    id: 84,
    name: "Chicken Kabsa",
    description: "Saudi Arabian rice dish with chicken and nuts.",
    price: 14.99,
    category: "saudi",
    image: "/images/kabsa-with-nuts.jpg",
    rating: 4.7,
    reviews: 93,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "30-35 min",
    calories: 440,
    tags: ["saudi", "kabsa", "nuts"]
  },
  {
    id: 85,
    name: "Chicken Ful Medames",
    description: "Egyptian fava bean stew with chicken.",
    price: 11.99,
    category: "egyptian",
    image: "/images/ful-medames.jpg",
    rating: 4.5,
    reviews: 72,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "25-30 min",
    calories: 340,
    tags: ["egyptian", "ful medames", "fava beans"]
  },
  {
    id: 86,
    name: "Chicken Chana Masala",
    description: "Indian chickpea curry with chicken pieces.",
    price: 13.49,
    category: "indian",
    image: "/images/chana-masala.jpg",
    rating: 4.6,
    reviews: 88,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "25-30 min",
    calories: 380,
    tags: ["indian", "chana masala", "curry"]
  },
  {
    id: 87,
    name: "Chicken Paprikash",
    description: "Hungarian paprika stew with chicken and dumplings.",
    price: 14.49,
    category: "hungarian",
    image: "/images/chicken-paprikash.jpg",
    rating: 4.6,
    reviews: 84,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "30-35 min",
    calories: 410,
    tags: ["hungarian", "paprika", "stew"]
  },
  {
    id: 88,
    name: "Chicken Jollof Pasta",
    description: "West African jollof rice with pasta and chicken.",
    price: 13.99,
    category: "west-african",
    image: "/images/jollof-pasta.jpg",
    rating: 4.5,
    reviews: 79,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "20-25 min",
    calories: 420,
    tags: ["west-african", "jollof", "pasta"]
  },
  {
    id: 89,
    name: "Chicken Kottu",
    description: "Sri Lankan flatbread stir-fry with chicken.",
    price: 13.49,
    category: "sri-lankan",
    image: "/images/chicken-kottu.jpg",
    rating: 4.6,
    reviews: 87,
    popular: false,
    available: true,
    spiceLevel: 4,
    prepTime: "20-25 min",
    calories: 390,
    tags: ["sri-lankan", "kottu", "flatbread"]
  },
  {
    id: 90,
    name: "Chicken Bún Măm",
    description: "Vietnamese rice vermicelli with grilled chicken.",
    price: 12.99,
    category: "vietnamese",
    image: "/images/bun-mam.jpg",
    rating: 4.6,
    reviews: 91,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "15-18 min",
    calories: 360,
    tags: ["vietnamese", "bun mam", "vermicelli"]
  },
  {
    id: 91,
    name: "Chicken Bánh Xèo",
    description: "Vietnamese crispy pancake with chicken and vegetables.",
    price: 11.99,
    category: "vietnamese",
    image: "/images/banh-xeo.jpg",
    rating: 4.5,
    reviews: 75,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "18-22 min",
    calories: 340,
    tags: ["vietnamese", "banh xeo", "pancake"]
  },
  {
    id: 92,
    name: "Chicken Mafe",
    description: "West African peanut stew with chicken.",
    price: 13.99,
    category: "west-african",
    image: "/images/chicken-mafe.jpg",
    rating: 4.6,
    reviews: 83,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "30-35 min",
    calories: 380,
    tags: ["west-african", "mafe", "peanut"]
  },
  {
    id: 93,
    name: "Chicken Bobotie Pie",
    description: "South African pie with bobotie spiced chicken.",
    price: 12.99,
    category: "south-african",
    image: "/images/bobotie-pie.jpg",
    rating: 4.6,
    reviews: 80,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "30-35 min",
    calories: 400,
    tags: ["south-african", "bobotie", "pie"]
  },
  {
    id: 94,
    name: "Chicken Khorak",
    description: "Georgian chicken stew with walnuts and herbs.",
    price: 14.49,
    category: "georgian",
    image: "/images/chicken-khorak.jpg",
    rating: 4.7,
    reviews: 89,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "35-40 min",
    calories: 390,
    tags: ["georgian", "khorak", "walnuts"]
  },
  {
    id: 95,
    name: "Chicken Shashlik",
    description: "Caucasian grilled chicken skewers with spices.",
    price: 13.99,
    category: "caucasian",
    image: "/images/chicken-shashlik.jpg",
    rating: 4.6,
    reviews: 86,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "20-25 min",
    calories: 370,
    tags: ["caucasian", "shashlik", "skewers"]
  },
  {
    id: 96,
    name: "Chicken Manti",
    description: "Turkish dumplings with chicken filling and yogurt.",
    price: 14.99,
    category: "turkish",
    image: "/images/chicken-manti.jpg",
    rating: 4.7,
    reviews: 94,
    popular: true,
    available: true,
    spiceLevel: 2,
    prepTime: "35-40 min",
    calories: 420,
    tags: ["turkish", "manti", "dumplings"]
  },
  {
    id: 97,
    name: "Chicken Khao Soi",
    description: "Northern Thai curry noodles with chicken.",
    price: 13.49,
    category: "thai",
    image: "/images/chicken-khao-soi.jpg",
    rating: 4.7,
    reviews: 102,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "20-25 min",
    calories: 400,
    tags: ["thai", "khao soi", "curry noodles"]
  },
  {
    id: 98,
    name: "Chicken Bánh Cuốn",
    description: "Vietnamese steamed rolls with chicken filling.",
    price: 11.49,
    category: "vietnamese",
    image: "/images/banh-cuon.jpg",
    rating: 4.5,
    reviews: 78,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "15-18 min",
    calories: 320,
    tags: ["vietnamese", "banh cuon", "steamed"]
  },
  {
    id: 99,
    name: "Chicken Sambusak",
    description: "Middle Eastern pastries filled with chicken.",
    price: 10.99,
    category: "middle-eastern",
    image: "/images/chicken-sambusak.jpg",
    rating: 4.4,
    reviews: 71,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "25-30 min",
    calories: 300,
    tags: ["middle-eastern", "sambusak", "pastries"]
  },
  {
    id: 100,
    name: "Chicken Ful Medames Bowl",
    description: "Egyptian fava beans with chicken and vegetables.",
    price: 12.49,
    category: "egyptian",
    image: "/images/ful-bowl.jpg",
    rating: 4.5,
    reviews: 85,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "20-25 min",
    calories: 360,
    tags: ["egyptian", "ful medames", "bowl"]
  },
  {
    id: 101,
    name: "Chicken Burger",
    description: "Juicy grilled chicken burger with fresh vegetables.",
    price: 11.99,
    category: "burgers",
    image: "/images/chicken-burger.jpg",
    rating: 4.7,
    reviews: 92,
    popular: true,
    available: true,
    spiceLevel: 2,
    prepTime: "15-20 min",
    calories: 420,
    tags: ["burgers", "grilled", "sandwich"]
  },
  {
    id: 102,
    name: "Spicy Chicken Tacos",
    description: "Three soft tacos with seasoned chicken and spicy sauce.",
    price: 10.99,
    category: "tacos",
    image: "/images/chicken-tacos.jpg",
    rating: 4.6,
    reviews: 87,
    popular: false,
    available: true,
    spiceLevel: 4,
    prepTime: "12-15 min",
    calories: 380,
    tags: ["tacos", "mexican", "spicy"]
  },
  {
    id: 103,
    name: "Chicken Alfredo Pasta",
    description: "Fettuccine pasta with creamy chicken alfredo sauce.",
    price: 13.99,
    category: "pasta",
    image: "/images/chicken-pasta.jpg",
    rating: 4.5,
    reviews: 78,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "20-25 min",
    calories: 450,
    tags: ["pasta", "italian", "creamy"]
  },
  {
    id: 104,
    name: "BBQ Chicken Pizza",
    description: "Pizza with BBQ sauce, chicken, and melted cheese.",
    price: 14.99,
    category: "pizza",
    image: "/images/chicken-pizza.jpg",
    rating: 4.7,
    reviews: 101,
    popular: true,
    available: true,
    spiceLevel: 2,
    prepTime: "25-30 min",
    calories: 480,
    tags: ["pizza", "bbq", "cheesy"]
  },
  {
    id: 105,
    name: "Chicken Tikka Masala Pasta",
    description: "Pasta with creamy tikka masala chicken sauce.",
    price: 14.49,
    category: "curry",
    image: "/images/chicken-curry-pasta.jpg",
    rating: 4.6,
    reviews: 89,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "22-25 min",
    calories: 460,
    tags: ["curry", "pasta", "indian"]
  },
  {
    id: 106,
    name: "Chicken Noodle Soup",
    description: "Comforting soup with tender chicken and noodles.",
    price: 9.99,
    category: "soup",
    image: "/images/chicken-soup.jpg",
    rating: 4.4,
    reviews: 94,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "15-18 min",
    calories: 320,
    tags: ["soup", "comfort", "healthy"]
  },
  {
    id: 107,
    name: "Chicken Shawarma Kebab",
    description: "Spiced chicken kebab with tahini and vegetables.",
    price: 12.99,
    category: "kebab",
    image: "/images/chicken-kebab.jpg",
    rating: 4.7,
    reviews: 96,
    popular: true,
    available: true,
    spiceLevel: 3,
    prepTime: "18-22 min",
    calories: 400,
    tags: ["kebab", "middle-eastern", "spiced"]
  },
  {
    id: 108,
    name: "Chicken Ramen Noodles",
    description: "Rich broth with tender chicken and fresh noodles.",
    price: 11.49,
    category: "noodles",
    image: "/images/chicken-noodles.jpg",
    rating: 4.5,
    reviews: 85,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "15-20 min",
    calories: 380,
    tags: ["noodles", "ramen", "broth"]
  },
  {
    id: 109,
    name: "Crispy Chicken Caesar Wrap",
    description: "Crispy chicken with romaine lettuce and parmesan.",
    price: 10.49,
    category: "sandwiches",
    image: "/images/caesar-wrap.jpg",
    rating: 4.6,
    reviews: 81,
    popular: false,
    available: true,
    spiceLevel: 1,
    prepTime: "10-12 min",
    calories: 360,
    tags: ["sandwiches", "wrap", "caesar"]
  },
  {
    id: 110,
    name: "Spicy Buffalo Chicken Pasta",
    description: "Pasta with spicy buffalo chicken and ranch.",
    price: 13.99,
    category: "pasta",
    image: "/images/buffalo-pasta.jpg",
    rating: 4.5,
    reviews: 77,
    popular: false,
    available: true,
    spiceLevel: 4,
    prepTime: "20-25 min",
    calories: 440,
    tags: ["pasta", "buffalo", "spicy"]
  },
  {
    id: 111,
    name: "Chicken Tikka Pizza",
    description: "Pizza topped with Indian spiced chicken tikka.",
    price: 14.49,
    category: "pizza",
    image: "/images/tikka-pizza.jpg",
    rating: 4.6,
    reviews: 88,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "25-30 min",
    calories: 470,
    tags: ["pizza", "tikka", "indian"]
  },
  {
    id: 112,
    name: "Chicken Green Curry",
    description: "Thai green curry with tender chicken and vegetables.",
    price: 13.99,
    category: "thai",
    image: "/images/green-curry.jpg",
    rating: 4.7,
    reviews: 93,
    popular: true,
    available: true,
    spiceLevel: 4,
    prepTime: "22-25 min",
    calories: 410,
    tags: ["thai", "curry", "spicy"]
  },
  {
    id: 113,
    name: "Korean BBQ Chicken Bowl",
    description: "Rice bowl with Korean BBQ chicken and vegetables.",
    price: 12.99,
    category: "korean",
    image: "/images/korean-bowl.jpg",
    rating: 4.6,
    reviews: 86,
    popular: false,
    available: true,
    spiceLevel: 3,
    prepTime: "18-22 min",
    calories: 420,
    tags: ["korean", "bbq", "bowl"]
  },
  {
    id: 114,
    name: "Chicken Teriyaki Burger",
    description: "Burger with teriyaki glazed chicken and vegetables.",
    price: 12.49,
    category: "burgers",
    image: "/images/teriyaki-burger.jpg",
    rating: 4.5,
    reviews: 79,
    popular: false,
    available: true,
    spiceLevel: 2,
    prepTime: "12-15 min",
    calories: 430,
    tags: ["burgers", "teriyaki", "japanese"]
  },
  {
    id: 115,
    name: "Chicken Pho Soup",
    description: "Traditional Vietnamese noodle soup with chicken.",
    price: 11.99,
    category: "vietnamese",
    image: "/images/pho-soup.jpg",
    rating: 4.8,
    reviews: 102,
    popular: true,
    available: true,
    spiceLevel: 2,
    prepTime: "20-25 min",
    calories: 350,
    tags: ["vietnamese", "pho", "soup"]
  }
];

export const mockCategories = [
  { id: 'fried-chicken', name: 'Fried Chicken', icon: '🍗', itemCount: 15 },
  { id: 'wings', name: 'Chicken Wings', icon: '-wing', itemCount: 12 },
  { id: 'grilled-chicken', name: 'Grilled Chicken', icon: '🔥', itemCount: 10 },
  { id: 'sandwiches', name: 'Chicken Sandwiches', icon: '🥪', itemCount: 8 },
  { id: 'salads', name: 'Chicken Salads', icon: '🥗', itemCount: 6 },
  { id: 'combos', name: 'Combo Meals', icon: '🍽️', itemCount: 12 },
  { id: 'asian', name: 'Asian Chicken', icon: '🥢', itemCount: 15 },
  { id: 'indian', name: 'Indian Chicken', icon: '🍛', itemCount: 12 },
  { id: 'mexican', name: 'Mexican Chicken', icon: '🌮', itemCount: 10 },
  { id: 'italian', name: 'Italian Chicken', icon: '🍝', itemCount: 8 },
  { id: 'thai', name: 'Thai Chicken', icon: '🌶️', itemCount: 10 },
  { id: 'korean', name: 'Korean Chicken', icon: '🇰🇷', itemCount: 8 },
  { id: 'japanese', name: 'Japanese Chicken', icon: '🎌', itemCount: 7 },
  { id: 'southern', name: 'Southern Chicken', icon: '🍖', itemCount: 6 },
  { id: 'caribbean', name: 'Caribbean Chicken', icon: '🏝️', itemCount: 6 },
  { id: 'middle-eastern', name: 'Middle Eastern Chicken', icon: '🌙', itemCount: 7 },
  { id: 'greek', name: 'Greek Chicken', icon: '🏛️', itemCount: 5 },
  { id: 'vietnamese', name: 'Vietnamese Chicken', icon: '🇻🇳', itemCount: 7 },
  { id: 'fusion', name: 'Fusion Chicken', icon: '🔄', itemCount: 8 },
  { id: 'bowls', name: 'Chicken Bowls', icon: '🥣', itemCount: 11 },
  { id: 'burgers', name: 'Chicken Burgers', icon: '🍔', itemCount: 9 },
  { id: 'tacos', name: 'Chicken Tacos', icon: '🌮', itemCount: 8 },
  { id: 'pasta', name: 'Chicken Pasta', icon: '🍝', itemCount: 8 },
  { id: 'pizza', name: 'Chicken Pizza', icon: '🍕', itemCount: 7 },
  { id: 'curry', name: 'Chicken Curry', icon: '🍛', itemCount: 10 },
  { id: 'soup', name: 'Chicken Soup', icon: '🍲', itemCount: 7 },
  { id: 'kebab', name: 'Chicken Kebab', icon: '🥙', itemCount: 8 },
  { id: 'noodles', name: 'Chicken Noodles', icon: '🍜', itemCount: 9 }
];

export const menuService = {
  // Get all menu categories
  async getCategories() {
    try {
      const response = await api.get(ENDPOINTS.MENU.CATEGORIES);
      return response.data;
    } catch (error) {
      console.error('Get categories error:', error);
      // Return mock data if API fails
      return mockCategories;
    }
  },

  // Get menu items with filtering and pagination
  async getItems(filters = {}) {
    try {
      const params = {
        category: filters.category,
        search: filters.searchTerm,
        sort: filters.sortBy,
        page: filters.page || 1,
        limit: filters.limit || 20,
        ...filters,
      };

      const response = await api.get(ENDPOINTS.MENU.ITEMS, { params });
      return response.data;
    } catch (error) {
      console.error('Get items error:', error);
      // Return mock data if API fails
      let filteredItems = [...mockMenuItems];
      
      if (filters.category) {
        filteredItems = filteredItems.filter(item => item.category === filters.category);
      }
      
      if (filters.searchTerm) {
        const searchTerm = filters.searchTerm.toLowerCase();
        filteredItems = filteredItems.filter(item => 
          item.name.toLowerCase().includes(searchTerm) ||
          item.description.toLowerCase().includes(searchTerm) ||
          item.tags.some(tag => tag.toLowerCase().includes(searchTerm))
        );
      }

      const page = filters.page || 1;
      const limit = filters.limit || 20;
      const startIndex = (page - 1) * limit;
      const endIndex = startIndex + limit;
      const paginatedItems = filteredItems.slice(startIndex, endIndex);

      return {
        items: paginatedItems,
        total: filteredItems.length,
        page: page,
        limit: limit,
        totalPages: Math.ceil(filteredItems.length / limit)
      };
    }
  },

  // Get item details
  async getItemDetails(itemId) {
    try {
      const response = await api.get(buildUrl(`${ENDPOINTS.MENU.ITEM_DETAILS}/:id`, { id: itemId }));
      return response.data;
    } catch (error) {
      console.error('Get item details error:', error);
      // Find item in mock data
      const item = mockMenuItems.find(item => item.id === parseInt(itemId));
      if (item) return item;
      throw new Error('Item not found');
    }
  },

  // Search menu items
  async searchItems(query, filters = {}) {
    try {
      const params = {
        q: query,
        ...filters,
      };

      const response = await api.get(ENDPOINTS.MENU.SEARCH, { params });
      return response.data;
    } catch (error) {
      console.error('Search items error:', error);
      // Search in mock data
      const searchTerm = query.toLowerCase();
      const results = mockMenuItems.filter(item => 
        item.name.toLowerCase().includes(searchTerm) ||
        item.description.toLowerCase().includes(searchTerm) ||
        item.tags.some(tag => tag.toLowerCase().includes(searchTerm))
      );
      
      return {
        items: results,
        total: results.length,
        page: 1,
        limit: results.length
      };
    }
  },

  // Get personalized recommendations
  async getRecommendations(limit = 10) {
    try {
      const params = { limit };
      const response = await api.get(ENDPOINTS.MENU.RECOMMENDATIONS, { params });
      return response.data;
    } catch (error) {
      console.error('Get recommendations error:', error);
      // Return popular items as recommendations
      const popularItems = mockMenuItems.filter(item => item.popular).slice(0, limit);
      return popularItems.length > 0 ? popularItems : mockMenuItems.slice(0, limit);
    }
  },

  // Get item customizations
  async getCustomizations(itemId) {
    try {
      const response = await api.get(buildUrl(`${ENDPOINTS.MENU.CUSTOMIZATIONS}/:id`, { id: itemId }));
      return response.data;
    } catch (error) {
      console.error('Get customizations error:', error);
      // Return default customizations
      return {
        id: itemId,
        options: [
          {
            name: "Spice Level",
            options: ["Mild", "Medium", "Hot", "Extra Hot"],
            default: "Medium"
          },
          {
            name: "Sauce",
            options: ["Original", "BBQ", "Honey Mustard", "Ranch"],
            default: "Original"
          },
          {
            name: "Sides",
            options: ["Fries", "Rice", "Salad", "Mashed Potatoes"],
            default: "Fries"
          }
        ]
      };
    }
  },

  // Check item availability
  async checkAvailability(itemId, quantity = 1) {
    try {
      const response = await api.get(`/menu/items/${itemId}/availability`, {
        params: { quantity },
      });
      return response.data;
    } catch (error) {
      console.error('Check availability error:', error);
      // Return mock availability
      const item = mockMenuItems.find(item => item.id === parseInt(itemId));
      return {
        available: item ? item.available : false,
        maxQuantity: item ? 50 : 0,
        estimatedWaitTime: "15-20 minutes"
      };
    }
  },

  // Get popular items
  async getPopularItems(limit = 8) {
    try {
      const response = await api.get('/menu/popular', { params: { limit } });
      return response.data;
    } catch (error) {
      console.error('Get popular items error:', error);
      // Return mock popular items if API fails
      return mockMenuItems.filter(item => item.popular).slice(0, limit);
    }
  },

  // Cache menu data
  cacheMenuData(category, data) {
    const cacheKey = `menu_${category}`;
    storageService.set(cacheKey, data, 5 * 60 * 1000); // 5 minutes cache
  },

  // Get cached menu data
  getCachedMenuData(category) {
    const cacheKey = `menu_${category}`;
    return storageService.get(cacheKey);
  },
};